coverage:
  status:
    # Configuration for project-level checks. This checks how the PR changes overall coverage.
    project:
      default:
        target: auto
        threshold: 3%
comment: true
ignore:
  - src/tests
  - src/maastesting
  - src/perftests
  - src/maasserver/migrations
  - src/maasserver/testing
  - "*/tests/*"
  - "*/testing/*"
  - setup.py
  - versioneer.py
