name: maas
adopt-info: maas
summary: Metal as a Service
description: |
  Total automation of your physical servers for amazing data center operational efficiency.
grade: stable
confinement: strict
base: core18
assumes:
  - snapd2.41
system-usernames:
  snap_daemon: shared
# epochs:
#
# 0: MAAS 2.5 PostgreSQL 9.5
# 1: MAAS 2.6+ PostgreSQL 10
# 2: MAAS 2.8+ Move MAAS data to $SNAP_COMMON
epoch: 2*

plugs:
  maas-cli:
    interface: content
    content: maas-cli
    target: $SNAP/maas-cli/lib
    default-provider: maas-cli
  test-db-socket:
    interface: content
    content: db-socket
    target: $SNAP_COMMON/test-db-socket

apps:
  supervisor:
    daemon: simple
    command: bin/run-supervisord
    environment:
      LD_PRELOAD: $SNAP/usr/lib/stub_initgroups.so
    plugs:
        - avahi-observe # network discovery
        - hardware-observe
        - kernel-module-observe
        - mount-observe
        - network
        - network-bind
        - network-observe
        - network-control
        - system-observe
        - time-control # chrony

  maas:
    command: bin/ld-preload $SNAP/bin/maas
    plugs:
        - home
        - mount-observe  # to read /proc/*/mounts
        - network # for external authentication
        - network-bind # for connecting to PostgreSQL
        - network-observe # to get default URL

parts:
  maas-pypi:
    # Keep the pypi dependencies separate from the deb dependencies, so
    # that the pypi and deb versions of the same packages won't conflict
    # when building the wheels
    plugin: python
    source: snap/local/pypi
    requirements:
      - requirements.txt
    build-packages:
      - build-essential
      - git
      - libffi-dev
      - libpq-dev
      - libssl-dev # XXX needed while we're getting pylxd from pypi
      - libxml2-dev
      - libxslt1-dev

  maas:
    plugin: python
    source: .
    after:
        # Make sure the pypi packages are built first, before we install
        # the deb versions of possible dependencies.
        - maas-pypi
    stage-packages:
      - amtterm                 # AMT
      - libsoap-lite-perl       # Dependencies for AMT
      - libxml-parser-perl      # Dependencies for AMT
      - libxml-parser-lite-perl # Dependencies for AMT
      - wsmancli                # AMT
      - snmp                    # APC
      - wget                    # DLI
      - freeipmi-tools          # IPMI
      - ipmitool                # Moonshot
      - libvirt-clients         # Virsh
      - archdetect-deb
      - avahi-utils
      - bind9
      - gpgv
      - iproute2
      - isc-dhcp-client
      - isc-dhcp-server
      - libatm1
      - libpq5
      - libxtables12
      - lshw
      - chrony
      - nginx-core
      - openssh-client
      - postgresql
      - python3-bson
      - python3-crochet
      - python3-django
      - python3-django-piston3
      - python3-djorm-ext-pgarray
      - python3-distro-info
      - python3-formencode
      - python3-httplib2
      - python3-jsonschema
      - python3-lxml
      - python3-mimeparse
      - python3-netaddr
      - python3-netifaces
      - python3-paramiko
      - python3-petname
      - python3-pexpect
      - python3-psycopg2
      - python3-pyparsing
      - python3-requests
      - python3-sphinx
      - python3-tempita
      - python3-twisted
      - python3-zope.interface
      - python3-seamicroclient
      - python3-txtftp
      - python3-yaml
      - python3-simplestreams
      - python3-curtin
      - python3-oauth
      - python3-oauthlib
      - python3-attr
      - python3-simplejson
      - python3-markupsafe
      - rsyslog
      - squid
      - tcpdump
      - ubuntu-keyring
      - util-linux
    # As a workaround to issues similar to https://pad.lv/1613898 we manually specify setuptools and wheel
    python-packages:
      - setuptools
      - wheel
    organize:
        lib/python3.*/site-packages/etc/*: etc
        lib/python3.*/site-packages/usr/bin/*: usr/bin
        lib/python3.*/site-packages/usr/lib/*: usr/lib
        lib/python3.*/site-packages/usr/sbin/*: usr/sbin
        lib/python3.*/site-packages/usr/share/*: usr/share
        usr/lib/curtin/helpers: usr/lib/python3/dist-packages/helpers
    filesets:
      remove:
        - -lib/python3.*/site-packages/etc
        - -lib/python3.*/site-packages/usr
        - -lib/python3/dist-packages/maastesting
        - -share
        - -usr/bin/xdg-*
        - -usr/share/applications
        - -usr/share/bug
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -usr/share/man
        - -var/lib/ieee-data/oui36.txt
        - -var/lib/ieee-data/mam.txt
    stage:
      - $remove
    prime:
      - $remove
    override-build: |
      set -e
      snapcraftctl build
      ln -s -f ../usr/lib/postgresql/10/bin/initdb $SNAPCRAFT_PART_INSTALL/bin/initdb
      ln -s -f ../usr/lib/postgresql/10/bin/pg_ctl $SNAPCRAFT_PART_INSTALL/bin/pg_ctl
      ln -s -f ../usr/lib/postgresql/10/bin/postgres $SNAPCRAFT_PART_INSTALL/bin/postgres
      ln -s -f ../usr/lib/postgresql/10/bin/psql $SNAPCRAFT_PART_INSTALL/bin/psql
      # If python3-netaddr contains absolute symlinks.
      # See https://bugs.launchpad.net/snapcraft/+bug/1774410
      ln -s -f ../../../../../../var/lib/ieee-data/oui.txt $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/oui.txt
      ln -s -f ../../../../../../var/lib/ieee-data/iab.txt $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/iab.txt
    override-prime: |
      set -e
      cwd=$(pwd)
      cd $SNAPCRAFT_PART_SRC
      snapcraftctl set-version $($SNAPCRAFT_PART_SRC/utilities/package-version)
      cd $cwd
      snapcraftctl prime
      $SNAPCRAFT_PART_INSTALL/usr/bin/python3 -m compileall -q .

  ui:
    plugin: nodejs
    source: src/maasui/src
    nodejs-version: "12.13.0"
    nodejs-yarn-version: "v1.19.1"
    build-packages:
      - on amd64: []
      - else:
          # node-sass on non-amd64 needs python 2, see http://pad.lv/1867329
          - python
    override-build: |
      set -e

      PATH="$PATH:$SNAPCRAFT_PART_BUILD/../npm/bin"
      NODE_ENV="production"
      yarn install
      yarn build-all

      INSTALL_DIR="$SNAPCRAFT_PART_INSTALL/usr/share/maas/web"
      mkdir -p "$INSTALL_DIR"
      cp -a build "$INSTALL_DIR/static"
    prime:
      - usr/share/maas/web/static

  machine-resources:
    plugin: make
    source: src/machine-resources
    build-snaps:
      - go/1.10/stable
    build-packages:
      - go-dep
    artifacts:
      - bin
    organize:
      bin: usr/share/maas/machine-resources

  tree:
    plugin: dump
    source: snap/local/tree

  stub-initgroups:
    plugin: make
    source: snap/local/stub_initgroups
    artifacts:
        - stub_initgroups.so
    organize:
        stub_initgroups.so: usr/lib/stub_initgroups.so
    prime:
        - usr/lib/stub_initgroups.so

  snapcraft-preload:
    plugin: cmake
    source: https://github.com/sergiusens/snapcraft-preload
    source-type: git
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib

hooks:
  install:
    plugs:
      - mount-observe  # to read /proc/*/mounts
      - network  # to connect to the db for running upgrades
  post-refresh:
    plugs:
      - mount-observe  # to read /proc/*/mounts
      - network  # to connect to the db for running upgrades

layout:
  /etc/libvirt:
    bind: $SNAP/etc/libvirt
  /usr/sbin/ipmi-config:
    bind-file: $SNAP/usr/sbin/ipmi-config
  /etc/freeipmi:
    bind: $SNAP/etc/freeipmi
  /root:
    bind: $SNAP_DATA/root
