name: Continuous delivery

on:
  push:
    branches:
      - master

jobs:
  snap:
    runs-on: [self-hosted, large-runner] 
    timeout-minutes: 120
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Clone test repo
      run: |
        git clone https://github.com/r00ta/r00tabot-runner-config.git /tmp/r00tabot-runner-config
        git config --global --add safe.directory /tmp/r00tabot-runner-config
    - name: chmod
      run: find /tmp/r00tabot-runner-config -type f -iname "*.sh" -exec chmod +x {} +
    - name: test
      run: TYPE=snap /tmp/r00tabot-runner-config/pipeline/execute.sh --maas_dir $PWD
  deb:
    runs-on: [self-hosted, large-runner] 
    timeout-minutes: 120
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Clone test repo
      run: |
        git clone https://github.com/r00ta/r00tabot-runner-config.git /tmp/r00tabot-runner-config
        git config --global --add safe.directory /tmp/r00tabot-runner-config
    - name: chmod
      run: find /tmp/r00tabot-runner-config -type f -iname "*.sh" -exec chmod +x {} +
    - name: test
      run: TYPE=deb /tmp/r00tabot-runner-config/pipeline/execute.sh --maas_dir $PWD
