name: CI

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  run:
    if: ${{ github.event.label.name == 'ci-test' }}
    runs-on: [self-hosted, quantagrid] 
    steps:
    - uses: actions/checkout@v4
    - name: create lxd container
      run: lxc launch ubuntu:22.04 maas-ci-tester-${{ github.sha }}
    - name: Sleep 10 seconds and wait for container to get up
      run: sleep 10 
    - name: Copy repository to lxd container
      run: lxc file push -r ./ maas-ci-tester-${{ github.sha }}/home/ubuntu
    - name: Install make
      run: lxc exec maas-ci-tester-${{ github.sha }} --user 0 -- sh -c "apt-get update && apt-get install make" 
    - name: Configure git repo
      run: lxc exec maas-ci-tester-${{ github.sha }} --user 0 -- git config --global --add safe.directory /home/ubuntu/maas
    - name: Make
      run: lxc exec maas-ci-tester-${{ github.sha }} --user 0 --cwd /home/ubuntu/maas/ -- make install-dependencies
    - name: Run Tests
      run: lxc exec maas-ci-tester-${{ github.sha }} --user 1000 --cwd /home/ubuntu/maas/ -- make test
    - name: cleanup
      if: always()
      run: lxc delete -f maas-ci-tester-${{ github.sha }}
