name: "AutoPR Manager"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write 
  pull-requests: write
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Process stale PRs
        uses: actions/stale@v9
        with:
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-stale: 1 # Mark stale after 8 weeks (56 days) of inactivity
          days-before-close: 1 # Disable auto-closing
          exempt-all-milestones: true # Any issue/PR within a milestone will be omitted
