name: "AutoPR Manager"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Process stale PRs
        uses: Sonia-corporation/stale@2.5.0
        with:
          issue-processing: false
          pull-request-days-before-stale: 1
          pull-request-days-before-close: 1
          pull-request-ignore-draft: true
          pull-request-ignore-all-milestones: true
          pull-request-stale-label: 'autoclose'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
