name: Smart code review
on:
  pull_request_target:
    types: [ labeled ]
permissions: write-all
jobs:
  code_review:
    if: ${{ github.event.label.name == 'autoreview' }}
    runs-on: [self-hosted, tester] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: spaghettihub/ai_code_review@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_ADDRESS: ${{ secrets.OLLAMA_ADDRESS }}
          exclude: "yarn.lock,dist/**"
