name: Codecov

on:
  pull_request_target:
    types: [ labeled ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:  
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'coverage'
    runs-on: [self-hosted, tester] 
    steps:
    - uses: actions/checkout@v4
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    - name: Checkout
      if: github.event.label.name == 'coverage'
      uses: actions/checkout@v3
    - name: Setup proxy
      run: echo "Acquire::http::Proxy \"http://172.0.2.161:8000\";" | sudo tee /etc/apt/apt.conf.d/00proxy
    - name: Install make
      run: sudo apt-get update && sudo apt-get install make 
    - name: Install deps
      run: |
        make install-dependencies 
        make
        sh -c ". .ve/bin/activate && pip install coverage gevent && deactivate"
    - name: Region coverage
      run: bin/test.region --with-coverage --cover-xml --cover-xml-file=./coverage-region.xml
    - name: Rack coverage
      run: bin/test.rack --with-coverage --cover-xml --cover-xml-file=./coverage-rack.xml
    - name: pytest coverage
      run: sh -c ". .ve/bin/activate && coverage run -a --source=. --concurrency=gevent --data-file=./coverage-pytest -m pytest && coverage xml -i --data-file coverage-pytest" 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        flags: smart-tests
        verbose: true
        directory: .
        files: coverage.xml, coverage-region.xml, coverage-rack.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
