name: Codecov

on:
  pull_request_target:
    types: [ labeled ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:  
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: | 
          make install-dependencies clean build cleandb syncdb
          source .ve/bin/activate && pip install coverage gevent
      - name: Region coverage
        run: bin/test.region --with-coverage --cover-xml --cover-xml-file=./coverage-region.xml
      - name: Rack coverage
        run: bin/test.rack --with-coverage --cover-xml --cover-xml-file=./coverage-rack.xml
      - name: pytest coverage
        run: |
          source .ve/bin/activate 
          coverage run -a --source=. --concurrency=gevent --data-file=./coverage-pytest -m pytest 
          coverage xml -i --data-file coverage-pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: smart-tests
          verbose: true
          files: ./coverage.xml, ./coverage-region.xml, ./coverage-rack.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
