name: Integration tests

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  snap:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: [self-hosted, tester] 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate env
      id: generate_env
      run: |
        echo "PIPELINE_DIR=$(mktemp -d)" >> $GITHUB_ENV
        echo "TYPE=snap" >> $GITHUB_ENV
    - name: Clone test repo
      run: |
        git config --global --add safe.directory $PIPELINE_DIR
        git clone https://github.com/r00ta/r00tabot-runner-config.git $PIPELINE_DIR
    - name: chmod
      run: find $PIPELINE_DIR -type f -iname "*.sh" -exec chmod +x {} +
    - name: test
      run: $PIPELINE_DIR/pipeline/execute.sh --maas_dir $PWD
  deb:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: [self-hosted, tester] 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate env
      id: generate_env
      run: |
        echo "PIPELINE_DIR=$(mktemp -d)" >> $GITHUB_ENV
        echo "TYPE=deb" >> $GITHUB_ENV
    - name: Clone test repo
      run: |
        git config --global --add safe.directory $PIPELINE_DIR
        git clone https://github.com/r00ta/r00tabot-runner-config.git $PIPELINE_DIR
    - name: chmod
      run: find $PIPELINE_DIR -type f -iname "*.sh" -exec chmod +x {} +
    - name: test
      run: $PIPELINE_DIR/pipeline/execute.sh --maas_dir $PWD
