name: Linter

on:
  pull_request_target:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4
    - name: Install make
      run: sudo apt-get update && sudo apt-get install make
    - name: Install dependencies
      run: make install-dependencies
    - name: Run Tests
      run: make lint
