name: Linter

on:
  pull_request_target:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: pip install tox
    - name: Run Tests
      run: make lint
