name: Mypy

on:
  pull_request_target:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Get changed Python files
      id: changed-files
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "$FILES" | grep '\.py$' || true
        echo "::set-output name=files::$FILES"
    - name: Run mypy
      if: steps.changed-files.outputs.files != ''
      run: |
        echo "${{ steps.changed-files.outputs.files }}" | xargs mypy
